
import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'index.ts',
    components: 'components/index.ts',
    hooks: 'hooks/index.ts',
    'state': 'state/index.ts',
    'types': 'types/index.ts',
    'components/dialogs/ChooseNetworkDialog': 'components/dialogs/ChooseNetworkDialog.tsx',
    'components/dialogs/SignMessageDialog': 'components/dialogs/SignMessageDialog.tsx',
    'components/dialogs/SwitchNetworkDialog': 'components/dialogs/SwitchNetworkDialog.tsx',
    'components/ConnectWalletDialog': 'components/ConnectWalletDialog.tsx',
    'components/dialogs/WatchTransactionDialog': 'components/dialogs/WatchTransactionDialog.tsx',
    'components/dialogs/HoldingKitDialog': 'components/dialogs/HoldingKitDialog.tsx',
    'components/dialogs/SelectCurrencyDialog': 'components/dialogs/SelectCurrencyDialog.tsx',
    'components/dialogs/SelectLanguageDialog': 'components/dialogs/SelectLanguageDialog.tsx',
    'components/mediaDialog': 'components/mediaDialog/index.tsx',
    'components/AppDialogTitle': 'components/AppDialogTitle.tsx',
    'components/CopyIconButton': 'components/CopyIconButton.tsx',
    'components/WalletContent': 'components/WalletContent.tsx',
    'components/AppDataTable': 'components/AppDataTable.tsx',
    'components/CompletationProvider': 'components/CompletationProvider.tsx',
    'providers/authProvider': 'providers/authProvider.tsx',
    'hooks/useSidebarVariant': 'hooks/useSidebarVariant.ts',
    'hooks/useBlockNumber': 'hooks/useBlockNumber.ts',
    'hooks/useDexKitContext': 'hooks/useDexKitContext.ts',
    'hooks/ui': 'hooks/ui.ts',
    'modules/nft': 'modules/nft/index.ts',
    'modules/nft/components': 'modules/nft/components/index.ts',
    'modules/nft/components/AssetCard': 'modules/nft/components/AssetCard.tsx',
    'modules/nft/types': 'modules/nft/types/index.ts',
    'modules/file/types': 'modules/file/types/index.ts',
    'modules/wallet/components/WalletAssetsFilter': 'modules/wallet/components/WalletAssetsFilter.tsx',
    'modules/nft/hooks': 'modules/nft/hooks/index.ts',
    'modules/forms/hooks': 'modules/forms/hooks/index.ts',
    'modules/forms/components/FormInfoCard': 'modules/forms/components/FormInfoCard.tsx',
    'modules/swap/hooks': 'modules/swap/hooks/index.ts',
    'modules/wizard/constants': 'modules/wizard/constants/index.ts',
    'modules/wizard/types/config': 'modules/wizard/types/config.ts',
    'modules/wallet/components/containers/EvmWalletContainer': 'modules/wallet/components/containers/EvmWalletContainer.tsx',
    'modules/commerce/components/containers/types': 'modules/commerce/components/containers/types/index.ts',
    'modules/commerce/components/containers/utils': 'modules/commerce/components/containers/utils.ts'
  },
  outDir: 'dist',
  platform: 'browser',
  dts: true
})